### ISSUE TITLE
Vista para Agregar Aspirantes

### ISSUE THREAD

**Issue by Memotets** [Memotets/ProyectoMovilesFlutter#6]
En la vista se tiene que hacer un formulario para agregar nuevos aspirante en donde se tiene que contemplar todos los campos y al enviar se tienen que validar la existencia de los campos

**Comment by HectorGG99** [comment]
![asda](https://user-images.githubusercontent.com/47466780/69209472-fc69bf80-0b1c-11ea-9c36-13149829b408.JPG)
Por qué crees que sea ese error? Si gustas checarlo (Alexis hará commit en breves), ya funciona todo, solo me da error en la parte de registrar por eso mismo de la imagen.

**Comment by Memotets** [comment]
No tengo la menor idea y mucho menos si fue solucionado

**Comment by Memotets** [comment]
ya funco

**Comment by Memotets** [comment]
Se debe agregar una lista de procedencias sacada de la base local, para poder registrar un aspirante
